//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demekz3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductTypeName { get; set; }
        public string ProductName { get; set; }
        public int VendorCode { get; set; }
        public string Materials { get; set; }
        public int ProductCost { get; set; }
        public string ImagePreview { get; set; }
    }
}
